POST http://localhost/login
Content-Type: application/json

{
  "email": "aallaguly01@gmail.com",
  "password": "B1gather"
}

###

GET http://localhost:80/teachers
X-TOKEN: 4a21ac01-1026-454a-9c82-ab0d09c85173

###

POST http://localhost/teachers
Content-Type: application/json

{
  "firstName": "Марсель",
  "lastName": "Сидиков"
}

###

POST http://localhost/teachers
Content-Type: application/json

{
  "firstName": "Михаил",
  "lastName": "Абрамский"
}

###

PUT http://localhost/teachers/1
Content-Type: application/json

{
  "firstName": "Марсель",
  "lastName": "Ситдиков"
}

###

DELETE http://localhost/teachers/1

###

GET http://localhost:8080/courses

###

POST http://localhost/courses
Content-Type: application/json

{
  "title": "Информатика"
}

###

POST http://localhost/courses/1/teachers
Content-Type: application/json

{
  "id": 1
}